name: Build/release

on:
  push:
    branches:
      - main
      - master

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: ENVFILE
        uses: alekangelov/secret-envfile@v1
        with:
          content: ${{ secrets.ELECTRON_PROD_ENV }}
          filename: .env.electron.prod

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1.6.0
        with:
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          github_token: ${{ secrets.github_token }}
          skip_build: false
          build_script_name: pre:dist
          args: "-c.extraMetadata.main=build/electron/main.js"
